variables:
  TARGET: MOKIT_manual

pages:
  stage: deploy
  image: ubuntu:22.04
  script:
  #- wget https://github.com/badboy/mdbook-toc/releases/download/0.10.0/mdbook-toc-0.10.0-x86_64-unknown-linux-gnu.tar.gz
  #- wget https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
  - tar xvzf mdbook-v*-x86_64-unknown-linux-gnu.tar.gz
  - tar xvzf mdbook-toc-*-x86_64-unknown-linux-gnu.tar.gz
  - chown root:root mdbook*
  - apt update -y
  - apt install chromium -y
  - ls -l
  - ./mdbook build
  - mv public/pdf/output.pdf public/pdf/${TARGET}.pdf
  artifacts:
    paths:
    - public
  only:
  - master
