variables:
  TARGET: MOKIT_manual

pages:
  stage: deploy
  image: ubuntu:22.04
  script:
  - tar xvzf mdbook-v*-x86_64-unknown-linux-gnu.tar.gz
  - tar xvzf mdbook-toc-*-x86_64-unknown-linux-gnu.tar.gz
  - chown root:root mdbook*
  - ls -l
  - ./mdbook build
  - mv public/pdf/output.pdf public/pdf/${TARGET}.pdf
  artifacts:
    paths:
    - public
  only:
  - master

pdf:
  rules:
    - if: $CI_COMMIT_TAG
  image: ubuntu:22.04
  before_script:
    - apt update -y
    - apt install chromium-browser -y
  script:
  - tar xvzf mdbook-v*-x86_64-unknown-linux-gnu.tar.gz
  - tar xvzf mdbook-toc-*-x86_64-unknown-linux-gnu.tar.gz
  - chown root:root mdbook*
  - ls -l
  - ./mdbook build
  - mv public/pdf/output.pdf public/pdf/${TARGET}.pdf
  artifacts:
    paths:
    - public/pdf/${TARGET}.pdf

