[book]
authors = [""]
language = "en"
multilingual = false
src = "src"
title = "MOKIT Documentation"

[build]
build-dir = "public"

[output.html]
#additional-css = ["./assets/custom.css"]
additional-css = [
  "theme/light.css",
  "theme/dark.css",
]
mathjax-support = true

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]
