[book]
authors = [""]
language = "en"
multilingual = false
src = "src"
title = "GitLab Pages mdbook Template"

[build]
build-dir = "public"

[output.html]
additional-css = ["./assets/custom.css"]

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]
