[book]
authors = [""]
language = "en"
multilingual = false
src = "src"
title = "MOKIT Documentation"

[build]
build-dir = "public"

[output.html]
#additional-css = ["./assets/custom.css"]
additional-css = [
  "theme/light.css",
  "theme/dark.css",
]
mathjax-support = true
git-repository-url = "https://gitlab.com/jeanwsr/mokit-doc-mdbook"
git-repository-icon = "fa-gitlab"
#additional-js = ["mermaid.min.js", "mermaid-init.js"]

#[output.markdown]

#[preprocessor.toc]
#command = "./mdbook-toc"
#renderer = ["html"]

#[preprocessor.mermaid]
#command = "./mdbook-mermaid"
